---

  - hosts: "k_pro_registry"
    gather_facts: True
    serial: "3"
    vars_files:
      - vars/pro/main.yml
      - vars/pro/d_registry.yml
      - vars/pro/docker.yml
    roles:
      - { role: k_docker_install }
      - { role: d_registry_install }
