---

  - hosts: "k_pro_master"
    gather_facts: True
    serial: "3"
    vars_files:
      - vars/pro/main.yml
      - vars/pro/apiserver.yml
    roles:
      - { role: k_apiserver_install }
      - { role: k_controllermanager_install }
      - { role: k_scheduler_install }

