# apiVersion: v1
# kind: Config
# preferences: {}

# clusters:
# - cluster:
#     certificate-authority: /data/cert/ca.crt
#     server: {{ KUBE_MASTER }}
# users:
# - name: controllermanager
#   user:
#     client-certificate: /data/cert/cs_client.crt
#     client-key: /data/cert/cs_client.key
# - contexts: 
#     cluster: mogo
#     user: controllermanager
#   name: kube-context
# current-context: kube-context
#
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /data/cert/ca.crt
    server: {{ KUBE_MASTER }}
  name: mogo
contexts:
- context:
    cluster: mogo
    namespace: default
    user: controllermanager
  name: kube-context
current-context: "kube-context"
kind: Config
preferences: {}
users:
- name: controllermanager
  user:
    client-certificate: /data/cert/cs_client.crt
    client-key: /data/cert/cs_client.key