apiVersion: v1
clusters:
- cluster:
    certificate-authority: /data/cert/ca.crt
    server: {{ KUBE_MASTER }}
  name: mogo
contexts:
- context:
    cluster: mogo
    namespace: default
    user: kubelet
  name: kube-context
current-context: "kube-context"
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /data/cert/kubelet_client.crt
    client-key: /data/cert/kubelet_client.key